// SPDX-License-Identifier: MIT
package com.xpdustry.nohorny.server.persistence;

import jakarta.persistence.MappedSuperclass;
import jakarta.persistence.PostLoad;
import jakarta.persistence.PostPersist;
import jakarta.persistence.Transient;
import org.springframework.data.domain.Persistable;

/// An entity whose identifier is assigned by the application rather than generated by the database.
///
/// Tracking whether it was persisted lets Spring Data insert new entities directly, instead of merging them, which
/// would select the row first.
@MappedSuperclass
public abstract class AssignedIdEntity<ID> implements Persistable<ID> {

    @Transient
    private boolean persisted = false;

    @Override
    public boolean isNew() {
        return !this.persisted;
    }

    @PostLoad
    @PostPersist
    void markPersisted() {
        this.persisted = true;
    }
}
