// Generated by filesystem-routing. Do not edit.
// Regenerated whenever a route file is added, changed or removed.

declare module "virtual:file-routes" {
  /** A code-split ref: the delivery adapter emits it as a dynamic import. */
  export interface FileRouteLazyRef<M = Record<string, unknown>> {
    src: string;
    import(): Promise<M>;
  }

  /** An eager ref: its picked exports are imported statically. */
  export interface FileRouteEagerRef<M = Record<string, unknown>> {
    /** The source module path — present when the convention emitted the ref lazy and `codeSplitting: false` delivered it eagerly. */
    src?: string;
    require(): M;
  }

  /** A flat entry of the route manifest. */
  export interface FileRouteEntry {
    path: string;
    page?: boolean;
    /** The page component is a server function; its `$component` is delivered eagerly. */
    server?: boolean;
    $component?: FileRouteLazyRef<any> | FileRouteEagerRef<any>;
    $$route?: FileRouteEagerRef<any>;
    [key: string]: unknown;
  }

  /** An entry of the nested `pageRoutes` view. */
  export interface FileRouteTreeEntry extends FileRouteEntry {
    id: string;
    children?: readonly FileRouteTreeEntry[];
  }

  /** The flat route manifest, in scan order. */
  const routes: readonly [
    {
      path: "/(site)";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(site)")>;
      $$route?: undefined;
    },
    {
      path: "/(site)/*404";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(site)/[...404]")>;
      $$route?: undefined;
    },
    {
      path: "/(site)/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(site)/index")>;
      $$route?: undefined;
    },
    {
      path: "/(site)/privacy";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(site)/privacy")>;
      $$route?: undefined;
    },
    {
      path: "/(site)/requests/:id";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(site)/requests/[id]")>;
      $$route?: undefined;
    },
    {
      path: "/admin";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin")>;
      $$route?: undefined;
    },
    {
      path: "/admin/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/index")>;
      $$route?: undefined;
    },
    {
      path: "/admin/users";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/users")>;
      $$route?: undefined;
    }
  ];
  export default routes;

  /** The page entries, nested by path with grouping segments stripped. */
  export const pageRoutes: readonly [
    {
      path: "/admin";
      id: "/admin";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin")>;
      $$route?: undefined;
      children: readonly [
        {
          path: "/";
          id: "/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/admin/index")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/users";
          id: "/users";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/admin/users")>;
          $$route?: undefined;
          children?: undefined;
        }
      ];
    },
    {
      path: "/";
      id: "/(site)";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(site)")>;
      $$route?: undefined;
      children: readonly [
        {
          path: "/";
          id: "/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(site)/index")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/*404";
          id: "/*404";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(site)/[...404]")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/privacy";
          id: "/privacy";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(site)/privacy")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/requests/:id";
          id: "/requests/:id";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(site)/requests/[id]")>;
          $$route?: undefined;
          children?: undefined;
        }
      ];
    }
  ];
}
