spring.application.name=nohorny
spring.web.error.whitelabel.enabled=false

nohorny.classifier.vit.repository=phinner/nsfw_image_detection
nohorny.classifier.vit.revision=aab8ebd004112c8358a8ff9709c0492c2ba96bdc
nohorny.classifier.vit.file=falconsai_nsfw_image_detection.pt
nohorny.classifier.vit.labels=normal,nsfw
nohorny.classifier.vit.nsfw-label=nsfw
nohorny.classifier.vit.directory=.cached-models
nohorny.classifier.vit.engine=PyTorch
nohorny.classifier.vit.thresholds.nsfw=0.7
nohorny.classifier.vit.thresholds.warn=0.4
