client:
  endpoint: https://nohorny.xpdustry.com
  timeout: 10s
  displays:
    processing-threshold: 0.3
    processing-delay: 5s
    minimum-group-size: 1
    minimum-processor-count: 3
    minimum-instruction-count: 100
    processor-search-radius: 10
  canvases:
    processing-threshold: 0.3
    processing-delay: 5s
    minimum-group-size: 9
    minimum-palette-size: 3
  auto-mod:
    ban-on: NSFW
    delete-on: WARN
